const PptxGenJS = require('pptxgenjs');
const fs = require('fs/promises');
const { safePath, relativePath, withExtension, ensureParent, writeSidecar, readSidecar, fileInfo } = require('./officeCommon');

const THEMES = {
  'corporate-light': { bg:'F6F8FC', text:'18212F', accent:'2563EB', accent2:'0EA5E9', muted:'667085', card:'FFFFFF', soft:'EAF1FF', line:'D7DFEA' },
  'corporate-dark': { bg:'0B1220', text:'F8FAFC', accent:'38BDF8', accent2:'818CF8', muted:'A3B2C7', card:'162033', soft:'1C2A42', line:'31415C' },
  minimal: { bg:'FFFFFF', text:'111111', accent:'111111', accent2:'6B7280', muted:'6B7280', card:'F7F7F7', soft:'F1F1F1', line:'E5E5E5' },
  training: { bg:'F7FAF9', text:'12332D', accent:'0F766E', accent2:'14B8A6', muted:'60736E', card:'FFFFFF', soft:'E6F4F1', line:'D4E4DF' },
  executive: { bg:'F4F0E8', text:'20201E', accent:'7C3E2F', accent2:'B7794B', muted:'706A61', card:'FFFDF8', soft:'EDE3D5', line:'D9CDBE' },
  tech: { bg:'07111E', text:'F0F9FF', accent:'22D3EE', accent2:'A78BFA', muted:'8AA4B7', card:'0E2032', soft:'102A40', line:'1C405A' },
  editorial: { bg:'FBF8F2', text:'191919', accent:'D04A35', accent2:'1F6F78', muted:'6F6A63', card:'FFFFFF', soft:'F0E9DE', line:'DDD3C6' },
  consulting: { bg:'FFFFFF', text:'17202A', accent:'0B5CAB', accent2:'00A3A3', muted:'66788A', card:'F7F9FC', soft:'EAF2FB', line:'D5DEE8' }
};
const TYPES = ['title','section','bullets','two_column','table','chart','quote','blank','hero_statement','hero_number','kpi_cards','three_cards','comparison','before_after','process','timeline','matrix','data_story','chart_insight','closing'];
const VISUAL_TYPES = new Set(['hero_statement','hero_number','kpi_cards','three_cards','comparison','before_after','process','timeline','matrix','data_story','chart_insight','quote']);

const arr=v=>Array.isArray(v)?v:[];
const str=v=>v===null||v===undefined?'':String(v);
const arrStr=v=>arr(v).map(str);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
function normalizeChart(c){if(!c||typeof c!=='object')return null;return{type:['bar','column','line','pie','doughnut'].includes(c.type)?c.type:'column',categories:arrStr(c.categories),series:arr(c.series).map(s=>({name:str(s?.name||'Series'),values:arr(s?.values).map(v=>Number(v)||0)}))};}
function normalizeTable(t){if(!t||typeof t!=='object')return null;return{headers:arrStr(t.headers),rows:arr(t.rows).map(r=>arr(r).map(v=>typeof v==='object'?JSON.stringify(v):str(v)))};}
function normalizeSlide(s={}){return{type:TYPES.includes(s.type)?s.type:'bullets',title:str(s.title),subtitle:str(s.subtitle),eyebrow:str(s.eyebrow),statement:str(s.statement),takeaway:str(s.takeaway),metric_value:str(s.metric_value),metric_label:str(s.metric_label),metric_detail:str(s.metric_detail),bullets:arrStr(s.bullets),left_title:str(s.left_title),left_text:str(s.left_text),left_bullets:arrStr(s.left_bullets),right_title:str(s.right_title),right_text:str(s.right_text),right_bullets:arrStr(s.right_bullets),quote:str(s.quote),attribution:str(s.attribution),cards:arr(s.cards).slice(0,6).map(x=>({title:str(x?.title),text:str(x?.text),badge:str(x?.badge),value:str(x?.value)})),metrics:arr(s.metrics).slice(0,6).map(x=>({value:str(x?.value),label:str(x?.label),detail:str(x?.detail),trend:str(x?.trend)})),steps:arr(s.steps).slice(0,8).map((x,i)=>({title:str(x?.title||`Step ${i+1}`),text:str(x?.text),label:str(x?.label),value:str(x?.value)})),matrix:arr(s.matrix).slice(0,4).map(x=>({title:str(x?.title),text:str(x?.text),badge:str(x?.badge)})),table:normalizeTable(s.table),chart:normalizeChart(s.chart),notes:str(s.notes),density:['low','medium','high'].includes(s.density)?s.density:'medium'};}
function normalizeSpec(input={}){return{title:str(input.title||'Presentation'),subject:str(input.subject),author:str(input.author||'Dify for VS Code'),company:str(input.company),theme:THEMES[input.theme]?input.theme:'corporate-light',font_family:str(input.font_family||'Microsoft YaHei'),design_mode:['safe','polished','bold'].includes(input.design_mode)?input.design_mode:'polished',slides:arr(input.slides).map(normalizeSlide)};}

function text(slide,value,o={}){if(!value)return;slide.addText(str(value),{margin:0,breakLine:false,fit:'shrink',valign:'mid',...o});}
function box(pptx,slide,x,y,w,h,fill,line=fill){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,fill:{color:fill},line:{color:line,width:.7},radius:.08});}
function pill(pptx,slide,value,x,y,w,t,f){if(!value)return;box(pptx,slide,x,y,w,.34,t.soft,t.soft);text(slide,value,{x:x+.08,y:y+.03,w:w-.16,h:.26,fontFace:f,fontSize:10,bold:true,color:t.accent,align:'center'});}
function pageTitle(pptx,slide,s,t,f,i){if(s.eyebrow)pill(pptx,slide,s.eyebrow,.72,.32,Math.min(2.5,Math.max(1,.12*s.eyebrow.length+.55)),t,f);text(slide,s.title,{x:.72,y:s.eyebrow?.8:.48,w:11.5,h:.66,fontFace:f,fontSize:s.title.length>42?22:27,bold:true,color:t.text});slide.addShape(pptx.ShapeType.line,{x:.72,y:s.eyebrow?1.54:1.25,w:.95,h:0,line:{color:t.accent,width:3}});text(slide,String(i).padStart(2,'0'),{x:12.08,y:.48,w:.5,h:.24,fontFace:f,fontSize:9,color:t.muted,align:'right'});}
function bullets(pptx,slide,items,t,f,x,y,w,h,density='medium'){const list=items.slice(0,8);if(!list.length)return;const gap=density==='low'?.18:.09,row=Math.min(.82,(h-gap*Math.max(0,list.length-1))/list.length),size=Math.max(13,(density==='low'?20:density==='high'?15:18)-Math.max(0,list.length-5));list.forEach((v,n)=>{const yy=y+n*(row+gap);slide.addShape(pptx.ShapeType.ellipse,{x,y:yy+.18,w:.12,h:.12,fill:{color:t.accent},line:{color:t.accent}});text(slide,v,{x:x+.28,y:yy,w:w-.28,h:row,fontFace:f,fontSize:size,color:t.text});});}
function card(pptx,slide,c,x,y,w,h,t,f,n=0){box(pptx,slide,x,y,w,h,t.card,t.line);const accent=n%2?t.accent2:t.accent;slide.addShape(pptx.ShapeType.rect,{x,y,w:.055,h,fill:{color:accent},line:{color:accent}});if(c.badge)pill(pptx,slide,c.badge,x+.28,y+.24,Math.min(1.5,.12*c.badge.length+.5),t,f);const top=c.badge?y+.75:y+.34;if(c.value)text(slide,c.value,{x:x+.28,y:top,w:w-.56,h:.64,fontFace:f,fontSize:30,bold:true,color:accent});text(slide,c.title,{x:x+.28,y:c.value?top+.7:top,w:w-.56,h:.48,fontFace:f,fontSize:17,bold:true,color:t.text});text(slide,c.text,{x:x+.28,y:c.value?top+1.22:top+.58,w:w-.56,h:h-(c.value?1.55:1.02),fontFace:f,fontSize:13,color:t.muted,valign:'top'});}
function metric(pptx,slide,m,x,y,w,h,t,f,n=0){box(pptx,slide,x,y,w,h,t.card,t.line);const a=n%2?t.accent2:t.accent;text(slide,m.value,{x:x+.26,y:y+.28,w:w-.52,h:.72,fontFace:f,fontSize:32,bold:true,color:a});text(slide,m.label,{x:x+.26,y:y+1.02,w:w-.52,h:.4,fontFace:f,fontSize:14,bold:true,color:t.text});if(m.detail)text(slide,m.detail,{x:x+.26,y:y+1.46,w:w-.52,h:.56,fontFace:f,fontSize:11.5,color:t.muted,valign:'top'});if(m.trend)pill(pptx,slide,m.trend,x+.26,y+h-.5,Math.min(1.7,.12*m.trend.length+.5),t,f);}
function chart(pptx,slide,c,t,f,area){if(!c||!c.categories.length||!c.series.length)return false;const data=c.series.map(s=>({name:s.name,labels:c.categories,values:s.values}));let type=pptx.ChartType.bar;const o={...area,showLegend:c.series.length>1,showTitle:false,showValue:false,showBorder:false,legendPos:'b',chartColors:[t.accent,t.accent2,'16A34A','F59E0B','8B5CF6'],catAxisLabelFontFace:f,valAxisLabelFontFace:f,catAxisLabelFontSize:10,valAxisLabelFontSize:10};if(c.type==='line')type=pptx.ChartType.line;else if(c.type==='pie'){type=pptx.ChartType.pie;o.showPercent=true;}else if(c.type==='doughnut'){type=pptx.ChartType.doughnut;o.showPercent=true;o.holeSize=62;}else o.barDir=c.type==='bar'?'bar':'col';slide.addChart(type,data,o);return true;}

function render(pptx,slide,spec,index,warnings){const t=THEMES[spec.theme],f=spec.font_family,s=spec.slides[index-1];slide.background={color:t.bg};switch(s.type){
case'title':slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:4.05,h:7.5,fill:{color:t.accent},line:{color:t.accent}});text(slide,s.eyebrow||spec.company||'PRESENTATION',{x:4.75,y:1.25,w:6.8,h:.3,fontFace:f,fontSize:11,bold:true,color:t.accent,charSpacing:1.2});text(slide,s.title||spec.title,{x:4.75,y:1.85,w:7.5,h:1.8,fontFace:f,fontSize:(s.title||spec.title).length>28?34:43,bold:true,color:t.text});text(slide,s.subtitle,{x:4.78,y:3.9,w:6.8,h:.9,fontFace:f,fontSize:18,color:t.muted,valign:'top'});break;
case'section':text(slide,s.eyebrow||`SECTION ${String(index).padStart(2,'0')}`,{x:.82,y:1.55,w:3,h:.3,fontFace:f,fontSize:11,bold:true,color:t.accent,charSpacing:1.2});text(slide,s.title,{x:.82,y:2.1,w:10.8,h:1.25,fontFace:f,fontSize:s.title.length>36?30:39,bold:true,color:t.text});text(slide,s.subtitle,{x:.84,y:3.65,w:8.8,h:.7,fontFace:f,fontSize:17,color:t.muted});slide.addShape(pptx.ShapeType.line,{x:.82,y:5.25,w:11.4,h:0,line:{color:t.line,width:5}});slide.addShape(pptx.ShapeType.line,{x:.82,y:5.25,w:3.0,h:0,line:{color:t.accent,width:5}});break;
case'hero_statement':pill(pptx,slide,s.eyebrow,.82,.66,Math.min(2.3,.12*s.eyebrow.length+.6),t,f);text(slide,s.statement||s.title,{x:.82,y:1.45,w:8.1,h:3.5,fontFace:f,fontSize:(s.statement||s.title).length>72?29:39,bold:true,color:t.text});slide.addShape(pptx.ShapeType.rect,{x:9.5,y:0,w:3.83,h:7.5,fill:{color:t.soft},line:{color:t.soft}});text(slide,s.metric_value||String(index).padStart(2,'0'),{x:9.95,y:2.05,w:2.85,h:1.1,fontFace:f,fontSize:56,bold:true,color:t.accent,align:'center'});text(slide,s.metric_label,{x:10.08,y:3.3,w:2.58,h:.78,fontFace:f,fontSize:15,bold:true,color:t.text,align:'center'});text(slide,s.subtitle,{x:.84,y:5.38,w:7.6,h:.7,fontFace:f,fontSize:16,color:t.muted});break;
case'hero_number':pageTitle(pptx,slide,s,t,f,index);text(slide,s.metric_value||'0',{x:.82,y:1.78,w:5.1,h:2,fontFace:f,fontSize:(s.metric_value||'0').length>8?52:76,bold:true,color:t.accent});text(slide,s.metric_label||s.statement,{x:6.05,y:2.0,w:5.7,h:.92,fontFace:f,fontSize:24,bold:true,color:t.text});text(slide,s.metric_detail||s.subtitle,{x:6.07,y:3.08,w:5.45,h:1.2,fontFace:f,fontSize:16,color:t.muted,valign:'top'});break;
case'kpi_cards':pageTitle(pptx,slide,s,t,f,index);{const ms=s.metrics.slice(0,4),gap=.25,w=(11.82-gap*Math.max(0,ms.length-1))/Math.max(1,ms.length);ms.forEach((m,n)=>metric(pptx,slide,m,.76+n*(w+gap),1.82,w,3.55,t,f,n));if(!ms.length)warnings.push(`Slide ${index}: kpi_cards has no metrics.`);if(s.takeaway){box(pptx,slide,.76,5.72,11.82,.7,t.soft,t.soft);text(slide,s.takeaway,{x:1.02,y:5.87,w:11.3,h:.36,fontFace:f,fontSize:14.5,bold:true,color:t.text,align:'center'});}}break;
case'three_cards':pageTitle(pptx,slide,s,t,f,index);{const cs=s.cards.slice(0,3),gap=.28,w=(11.82-gap*2)/3;cs.forEach((c,n)=>card(pptx,slide,c,.76+n*(w+gap),1.78,w,4.7,t,f,n));if(!cs.length)warnings.push(`Slide ${index}: three_cards has no cards.`);}break;
case'comparison':case'before_after':case'two_column':pageTitle(pptx,slide,s,t,f,index);box(pptx,slide,.76,1.78,5.72,4.75,t.card,t.line);box(pptx,slide,6.86,1.78,5.72,4.75,t.card,t.line);text(slide,s.left_title||(s.type==='before_after'?'Before':'Option A'),{x:1.05,y:2.12,w:5.05,h:.48,fontFace:f,fontSize:20,bold:true,color:t.accent});text(slide,s.right_title||(s.type==='before_after'?'After':'Option B'),{x:7.15,y:2.12,w:5.05,h:.48,fontFace:f,fontSize:20,bold:true,color:t.accent2});text(slide,s.left_text,{x:1.05,y:2.75,w:5,h:.78,fontFace:f,fontSize:14,color:t.muted,valign:'top'});text(slide,s.right_text,{x:7.15,y:2.75,w:5,h:.78,fontFace:f,fontSize:14,color:t.muted,valign:'top'});bullets(pptx,slide,s.left_bullets,t,f,1.05,s.left_text?3.72:2.82,5.05,s.left_text?2.2:3.2,s.density);bullets(pptx,slide,s.right_bullets,t,f,7.15,s.right_text?3.72:2.82,5.05,s.right_text?2.2:3.2,s.density);break;
case'process':pageTitle(pptx,slide,s,t,f,index);{const ss=s.steps.slice(0,6),gap=.16,w=(11.82-gap*Math.max(0,ss.length-1))/Math.max(1,ss.length);ss.forEach((v,n)=>{const x=.76+n*(w+gap);box(pptx,slide,x,2.0,w,3.75,t.card,t.line);slide.addShape(pptx.ShapeType.ellipse,{x:x+w/2-.28,y:2.34,w:.56,h:.56,fill:{color:n%2?t.accent2:t.accent},line:{color:n%2?t.accent2:t.accent}});text(slide,String(n+1),{x:x+w/2-.18,y:2.47,w:.36,h:.18,fontFace:f,fontSize:11,bold:true,color:t.bg,align:'center'});text(slide,v.title,{x:x+.2,y:3.18,w:w-.4,h:.52,fontFace:f,fontSize:w<1.9?13:16,bold:true,color:t.text,align:'center'});text(slide,v.text,{x:x+.2,y:3.88,w:w-.4,h:1.3,fontFace:f,fontSize:w<1.9?10.5:12.5,color:t.muted,align:'center',valign:'top'});});if(!ss.length)warnings.push(`Slide ${index}: process has no steps.`);}break;
case'timeline':pageTitle(pptx,slide,s,t,f,index);{const ss=s.steps.slice(0,6);slide.addShape(pptx.ShapeType.line,{x:1.05,y:3.25,w:11,h:0,line:{color:t.line,width:2}});const gap=ss.length>1?10.8/(ss.length-1):0;ss.forEach((v,n)=>{const x=1.05+n*gap;slide.addShape(pptx.ShapeType.ellipse,{x:x-.13,y:3.12,w:.26,h:.26,fill:{color:t.accent},line:{color:t.accent}});text(slide,v.label||v.value||String(n+1),{x:x-.7,y:2.35,w:1.4,h:.4,fontFace:f,fontSize:11,bold:true,color:t.accent,align:'center'});text(slide,v.title,{x:x-.88,y:3.62,w:1.76,h:.52,fontFace:f,fontSize:13,bold:true,color:t.text,align:'center'});text(slide,v.text,{x:x-.95,y:4.2,w:1.9,h:1.1,fontFace:f,fontSize:10.5,color:t.muted,align:'center',valign:'top'});});if(!ss.length)warnings.push(`Slide ${index}: timeline has no items.`);}break;
case'matrix':pageTitle(pptx,slide,s,t,f,index);{const pos=[[.76,1.75],[6.86,1.75],[.76,4.18],[6.86,4.18]];s.matrix.slice(0,4).forEach((v,n)=>{const[x,y]=pos[n];box(pptx,slide,x,y,5.72,2.08,t.card,t.line);pill(pptx,slide,v.badge,x+.28,y+.22,Math.min(1.4,.12*v.badge.length+.5),t,f);text(slide,v.title,{x:x+.28,y:v.badge?y+.75:y+.36,w:5.1,h:.46,fontFace:f,fontSize:17,bold:true,color:n%2?t.accent2:t.accent});text(slide,v.text,{x:x+.28,y:v.badge?y+1.22:y+.9,w:5.1,h:.75,fontFace:f,fontSize:12.5,color:t.muted,valign:'top'});});if(s.matrix.length!==4)warnings.push(`Slide ${index}: matrix works best with four items.`);}break;
case'data_story':pageTitle(pptx,slide,s,t,f,index);text(slide,s.metric_value||'0',{x:.82,y:1.75,w:5.0,h:1.5,fontFace:f,fontSize:(s.metric_value||'0').length>8?50:70,bold:true,color:t.accent});text(slide,s.metric_label||s.statement,{x:.84,y:3.38,w:5.0,h:.78,fontFace:f,fontSize:21,bold:true,color:t.text});text(slide,s.metric_detail,{x:.84,y:4.3,w:5,h:.8,fontFace:f,fontSize:14,color:t.muted,valign:'top'});s.metrics.slice(0,3).forEach((m,n)=>metric(pptx,slide,m,6.65,1.78+n*1.55,5.65,1.32,t,f,n));break;
case'chart_insight':pageTitle(pptx,slide,s,t,f,index);if(!chart(pptx,slide,s.chart,t,f,{x:.72,y:1.67,w:8.15,h:4.9}))warnings.push(`Slide ${index}: chart_insight has incomplete data.`);box(pptx,slide,9.2,1.67,3.38,4.9,t.card,t.line);text(slide,'KEY INSIGHT',{x:9.5,y:2.02,w:2.75,h:.28,fontFace:f,fontSize:10,bold:true,color:t.accent,charSpacing:1});text(slide,s.takeaway||s.statement||'Add a concise takeaway.',{x:9.5,y:2.55,w:2.75,h:2.1,fontFace:f,fontSize:(s.takeaway||s.statement).length>80?16:20,bold:true,color:t.text});text(slide,s.subtitle,{x:9.5,y:4.95,w:2.75,h:.8,fontFace:f,fontSize:12.5,color:t.muted,valign:'top'});break;
case'table':pageTitle(pptx,slide,s,t,f,index);{const tb=s.table||{headers:[],rows:[]},rows=[];if(tb.headers.length)rows.push(tb.headers);rows.push(...tb.rows);if(rows.length)slide.addTable(rows.slice(0,20),{x:.76,y:1.65,w:11.82,h:5.05,border:{type:'solid',color:t.line,pt:.8},fill:t.card,color:t.text,fontFace:f,fontSize:rows.length>14?10.5:12.5,margin:.08,valign:'mid',autoFit:false});else warnings.push(`Slide ${index}: table has no rows.`);}break;
case'chart':pageTitle(pptx,slide,s,t,f,index);if(!chart(pptx,slide,s.chart,t,f,{x:.88,y:1.65,w:11.45,h:5}))warnings.push(`Slide ${index}: chart has incomplete data.`);break;
case'quote':text(slide,'“',{x:.8,y:1.3,w:1,h:1,fontFace:'Georgia',fontSize:72,bold:true,color:t.accent});text(slide,s.quote,{x:1.55,y:1.65,w:10.2,h:2.8,fontFace:f,fontSize:s.quote.length>120?24:31,bold:true,color:t.text});text(slide,s.attribution,{x:7.4,y:4.95,w:4.3,h:.5,fontFace:f,fontSize:14,color:t.muted,align:'right'});break;
case'closing':text(slide,s.eyebrow||'THANK YOU',{x:.82,y:1.2,w:2.5,h:.3,fontFace:f,fontSize:11,bold:true,color:t.accent,charSpacing:1.2});text(slide,s.statement||s.title||'Thank you',{x:.82,y:2,w:9.7,h:1.65,fontFace:f,fontSize:(s.statement||s.title).length>52?31:40,bold:true,color:t.text});text(slide,s.subtitle,{x:.84,y:4,w:7.7,h:.7,fontFace:f,fontSize:17,color:t.muted});slide.addShape(pptx.ShapeType.rect,{x:11.2,y:0,w:2.13,h:7.5,fill:{color:t.accent},line:{color:t.accent}});break;
case'blank':if(s.title)pageTitle(pptx,slide,s,t,f,index);break;
default:pageTitle(pptx,slide,s,t,f,index);text(slide,s.statement,{x:.82,y:1.62,w:10.8,h:.72,fontFace:f,fontSize:22,bold:true,color:t.text});bullets(pptx,slide,s.bullets,t,f,.92,s.statement?2.65:1.78,11.1,s.statement?3.75:4.65,s.density);if(s.bullets.length>8)warnings.push(`Slide ${index}: ${s.bullets.length} bullets may be visually dense.`);}
if(s.notes){try{slide.addNotes(s.notes);}catch{}}
}

function slideChars(s){return[s.title,s.subtitle,s.eyebrow,s.statement,s.takeaway,s.metric_label,s.metric_detail,s.quote,s.left_text,s.right_text,...s.bullets,...s.left_bullets,...s.right_bullets,...s.cards.flatMap(c=>[c.title,c.text,c.value]),...s.metrics.flatMap(m=>[m.value,m.label,m.detail]),...s.steps.flatMap(x=>[x.title,x.text]),...s.matrix.flatMap(x=>[x.title,x.text])].join('').length;}
function designReviewFromSpec(spec){let score=100;const findings=[],add=(slide,severity,message,penalty,recommendation)=>{score-=penalty;findings.push({slide,severity,message,recommendation});},types=spec.slides.map(s=>s.type);let visual=0;spec.slides.forEach((s,i)=>{const n=i+1,b=s.bullets.length+s.left_bullets.length+s.right_bullets.length,c=slideChars(s);if(VISUAL_TYPES.has(s.type))visual++;if(s.title.length>58)add(n,'medium','Title is too long.',4,'Shorten the title to one clear message.');if(c>700)add(n,'high','Slide is text-heavy.',8,'Split content or use cards, process, comparison, KPI, or data-story layouts.');else if(c>480)add(n,'medium','Slide density is high.',4,'Reduce secondary copy.');if(b>8)add(n,'high',`${b} bullets is too dense.`,8,'Use visual archetypes or split the slide.');else if(b>6)add(n,'medium',`${b} bullets may feel crowded.`,4,'Keep 4-6 short points.');if(s.type==='matrix'&&s.matrix.length!==4)add(n,'medium','Matrix should contain four quadrants.',4,'Provide four matrix items.');if((s.type==='chart'||s.type==='chart_insight')&&s.chart?.categories?.length>12)add(n,'medium','Chart has too many categories.',5,'Aggregate or highlight the most important values.');if(s.type==='table'&&s.table?.rows?.length>14)add(n,'medium','Table is too long for a slide.',5,'Show a summary and move detail to an appendix.');});let streak=1;for(let i=1;i<types.length;i++){if(types[i]===types[i-1]){streak++;if(streak===3)add(i+1,'medium',`Three consecutive ${types[i]} slides create monotony.`,5,'Switch to a contrasting archetype.');}else streak=1;}if(spec.slides.length>=6&&visual<Math.ceil(spec.slides.length*.35))add(0,'high','Deck relies too heavily on basic layouts.',10,'Use more hero, KPI, card, process, comparison, timeline, and data-story slides.');if(new Set(types).size<3&&spec.slides.length>=6)add(0,'medium','Deck has too little layout variety.',6,'Use at least 3-4 slide archetypes.');score=clamp(score,0,100);return{score,grade:score>=90?'excellent':score>=80?'good':score>=70?'revise':'poor',findings,recommendations:[...new Set(findings.map(f=>f.recommendation))].slice(0,10),slide_count:spec.slides.length,archetype_count:new Set(types).size,visual_slide_count:visual};}

async function buildPpt(input,full){const spec=normalizeSpec(input);if(!spec.slides.length)throw new Error('ppt_create requires at least one slide.');const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author=spec.author;pptx.company=spec.company;pptx.subject=spec.subject;pptx.title=spec.title;pptx.lang='zh-CN';pptx.theme={headFontFace:spec.font_family,bodyFontFace:spec.font_family,lang:'zh-CN'};const warnings=[];spec.slides.forEach((_,i)=>render(pptx,pptx.addSlide(),spec,i+1,warnings));const review=designReviewFromSpec(spec);warnings.push(...review.findings.filter(f=>f.severity==='high').map(f=>f.slide?`Slide ${f.slide}: ${f.message}`:f.message));await ensureParent(full);await pptx.writeFile({fileName:full});await writeSidecar(full,{format:'dify-office-ppt-spec',version:2,presentation:spec,design_review:review});return{spec,warnings,review};}
async function createPresentation(args={}){const full=safePath(withExtension(args.output_path,'.pptx')),{spec,warnings,review}=await buildPpt(args,full);return{success:true,...await fileInfo(full),slide_count:spec.slides.length,theme:spec.theme,design_mode:spec.design_mode,design_score:review.score,design_grade:review.grade,sidecar:`${relativePath(full)}.dify.json`,warnings,design_review:review};}
async function updatePresentation(args={}){const full=safePath(withExtension(args.path,'.pptx')),sidecar=await readSidecar(full);if(!sidecar?.presentation)throw new Error('This presentation has no Dify editable sidecar.');const spec=normalizeSpec(sidecar.presentation),action=str(args.action||'replace_slide'),i=Number(args.slide_index||0);if(action==='set_title')spec.title=str(args.title||spec.title);else if(action==='set_theme'){if(!THEMES[args.theme])throw new Error(`Unknown theme: ${args.theme}`);spec.theme=args.theme;}else if(action==='append_slide')spec.slides.push(normalizeSlide(args.slide||{}));else if(action==='delete_slide'){if(i<1||i>spec.slides.length)throw new Error(`slide_index must be between 1 and ${spec.slides.length}.`);spec.slides.splice(i-1,1);}else if(action==='replace_slide'){if(i<1||i>spec.slides.length)throw new Error(`slide_index must be between 1 and ${spec.slides.length}.`);spec.slides[i-1]=normalizeSlide(args.slide||{});}else throw new Error(`Unsupported ppt_update action: ${action}`);const{warnings,review}=await buildPpt(spec,full);return{success:true,...await fileInfo(full),slide_count:spec.slides.length,action,theme:spec.theme,design_score:review.score,design_grade:review.grade,warnings,design_review:review};}
async function inspectPresentation(args={}){const full=safePath(withExtension(args.path,'.pptx'));await fs.access(full);const sidecar=await readSidecar(full),info=await fileInfo(full);if(!sidecar?.presentation)return{success:true,...info,editable:false,message:'PPTX exists but has no Dify editable sidecar.'};const spec=normalizeSpec(sidecar.presentation),review=designReviewFromSpec(spec);return{success:true,...info,editable:true,title:spec.title,theme:spec.theme,design_mode:spec.design_mode,slide_count:spec.slides.length,design_review:review,slides:spec.slides.map((s,i)=>({index:i+1,type:s.type,title:s.title,bullet_count:s.bullets.length+s.left_bullets.length+s.right_bullets.length,card_count:s.cards.length,metric_count:s.metrics.length,step_count:s.steps.length,table_rows:s.table?.rows?.length||0,chart_series:s.chart?.series?.length||0})),...(args.include_spec?{spec}:{})};}
async function reviewPresentation(args={}){const full=safePath(withExtension(args.path,'.pptx'));await fs.access(full);const sidecar=await readSidecar(full);if(!sidecar?.presentation)return{success:false,error:'Design review requires a PPT generated by ppt_create.'};return{success:true,path:relativePath(full),...designReviewFromSpec(normalizeSpec(sidecar.presentation))};}
module.exports={createPresentation,updatePresentation,inspectPresentation,reviewPresentation,normalizeSlide,normalizeSpec,designReviewFromSpec,THEMES,TYPES};
